#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_BOARD_ROLE_GIMBAL (1U)
#define APP_BOARD_ROLE_CHASSIS (2U)
#define APP_BOARD_ROLE_SINGLE (3U)

#ifndef APP_BOARD_ROLE
#define APP_BOARD_ROLE APP_BOARD_ROLE_SINGLE
#endif

#define APP_DEVICE_LOCATION_GIMBAL (1U)
#define APP_DEVICE_LOCATION_CHASSIS (2U)

#ifndef APP_DR16_LOCATION
#define APP_DR16_LOCATION APP_DEVICE_LOCATION_CHASSIS
#endif

#ifndef APP_FEEDER_LOCATION
#define APP_FEEDER_LOCATION APP_DEVICE_LOCATION_CHASSIS
#endif

#define APP_COMMAND_PERIOD_MS (5U)
#define APP_CHASSIS_PERIOD_MS (5U)
#define APP_GIMBAL_PERIOD_MS (2U)
#define APP_IMU_PERIOD_MS (1U)
#define APP_SHOOTER_PERIOD_MS (5U)

#define APP_GIMBAL_MAX_YAW_RATE_RAD_PER_S (3.5F)
#define APP_GIMBAL_MAX_PITCH_RATE_RAD_PER_S (2.0F)
#define APP_GIMBAL_MIN_PITCH_RAD (-0.50F)
#define APP_GIMBAL_MAX_PITCH_RAD (0.45F)

#define APP_CHASSIS_MAX_VELOCITY_M_PER_S (3.0F)
#define APP_CHASSIS_MAX_SPIN_RAD_PER_S (6.0F)
#define APP_CHASSIS_FOLLOW_GAIN (4.0F)
#define APP_CHASSIS_STOP_DEADBAND (0.02F)

#define APP_BOARD_COMM_BASE_IDENTIFIER (0x500U)

#if (APP_DR16_LOCATION != APP_DEVICE_LOCATION_GIMBAL) &&                                  \
    (APP_DR16_LOCATION != APP_DEVICE_LOCATION_CHASSIS)
#error "APP_DR16_LOCATION must select the gimbal or chassis board"
#endif

#if (APP_FEEDER_LOCATION != APP_DEVICE_LOCATION_GIMBAL) &&                                 \
    (APP_FEEDER_LOCATION != APP_DEVICE_LOCATION_CHASSIS)
#error "APP_FEEDER_LOCATION must select the gimbal or chassis board"
#endif

#endif
